apiVersion: 1

datasources:
  - name: InfluxDB v3
    type: influxdata-flightsql-datasource
    access: proxy
    basicAuth: false
    isDefault: true
    editable: true
    jsonData:
      host: "idm-influxdb:8181"
      secure: false
      token: "tokentokentokentokentokentokentokentokentokentokentokentokentokentokentokentokentokentokentokentoken"
      defaultDatabase: "idm_heatpump"
    secureJsonData:
      token: "tokentokentokentokentokentokentokentokentokentokentokentokentokentokentokentokentokentokentokentoken"
