apiVersion: 1

datasources:
  - name: InfluxDB v3
    type: influxdata-flightsql-datasource
    access: proxy
    basicAuth: false
    isDefault: true
    editable: true
    jsonData:
      host: "idm-influxdb:8181"
      secure: false
      token: "apiv3_nrU34Yi61Oka4Am3zPqyQXPaQt7vP4FmTQ7IgLlD0fx1ci8cUQSTwursMLpebvcHU8WZH5Zz3rQAFTVqR9p_aw"
      defaultDatabase: "idm_heatpump"
    secureJsonData:
      token: "apiv3_nrU34Yi61Oka4Am3zPqyQXPaQt7vP4FmTQ7IgLlD0fx1ci8cUQSTwursMLpebvcHU8WZH5Zz3rQAFTVqR9p_aw"
