apiVersion: 1

datasources:
  - name: VictoriaMetrics
    type: prometheus
    uid: VictoriaMetrics
    access: proxy
    url: http://victoriametrics:8428/prometheus
    isDefault: true
    editable: true
    version: 1
    jsonData:
      timeInterval: "30s"
